= DebugWebModule
Arne Vandamme
2.0.0.RELEASE
:toc: left
:sectanchors:
:module-version: 2.0.0.RELEASE
:module-name: DebugWebModule
:module-artifact: debug-web-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/DebugWebModule
:application-info-url: https://foreach.atlassian.net/wiki/display/AX/ApplicationInfoModule
:spring-security-module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityModule

[copyright,verbatim]
--
Copyright (C) 2014-2015 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
{module-name} provides a <<configure-root-path,configurable endpoint>> for developer related web resources from other modules.  It allows other modules to <<creating-your-own, register
one or more debug web controllers>> upon the presence of the {module-name}.  A typical example of a debug web controller
would be a controller to introspect and manage the cache.  Out of the box {module-name} comes with a <<default-debug-controllers,set of default controllers>>
that allow you to introspect the running `AcrossContext`.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

{module-name} only has a required dependency on AcrossWebModule.

=== Module settings

All properties start with the *debugWebModule.* prefix.

|===
|Property |Type |Description |Default

|root-path
|`String`
|Root path for all debug web controllers.  All mappings will be relative to this path.
|/debug

|dashboard
|`String`
|Path within the debug web context for the initial dashboard.
|/

|properties.masks
|`String[]`
|Set regular expressions for all property names that should be masked.
|`.\*password.*`, `.\*secret.*`

|properties.masked-properties
|`String[]`
|Set explicit property names that should be masked.
|

|security.enabled
|`String`
|Should the root path be secured with Basic Authentication.
|`true`

|security.username
|`String`
|The username to use for Basic Authentication to access the root path. +
Leave blank to disable the in-memory user.
|debug

|security.password
|`String`
|The password to use for Basic Authentication to access the root path.
|

|security.ip-addresses
|`String`
|The comma separated list of IP addresses that will always have access to the root path, without needing Basic Authentication.
|

|security.authority
|`String`
|The authority that an authenticated principal should have for accessing debug web. +
Useful if you want to share a global security configuration.
|ROLE_DEBUG_USER

|===

== What's new in this version?
:numbered!:
=== 2.0.0.RELEASE

* *Requires Across 2.0.0.*
* Context browser now shows event handler methods grouped by event instead of bean instance.
* The root path is now by default secured, it can be disabled with the `debugWebModule.security.enabled=false` property.

=== 1.0.1.RELEASE

* both root path and dashboard path are now configurable through properties
* the context browser debug controller can now mask sensitive property values

=== 1.0.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
== How {module-name} works

{module-name} creates a new `RequestMappingHandlerMapping` endpoint that serves all `@RequestMapping` methods from
beans annotated with `@DebugWebController`.  All mappings will be prefixed with the configured root path (eg: _/debug_) ensuring
that all web controllers are behind a base path.  Under the hood, {module-name} achieves this by creating a specific `PrefixingRequestMappingHandlerMapping`
 instance named _{module-name}_.

All `@DebugWebController` instances are automatically mapped on the default debug web layout template.  The template takes
  care of dynamically building a top menu where controllers can position themselves.  For output rendering a http://www.thymeleaf.org[Thymeleaf]
  template based on http://www.getbootstrap.com[Bootstrap] and http://www.jquery.com[JQuery] is used.

== Configuring {module-name}

[[configure-root-path]]
=== Root path

The root path is configured by setting the `debugWebModule.root-path` property.
This can only be done when configuring the `AcrossContext`, before it has bootstrapped.
If no custom root path is configured, the default is */debug*.

=== Dashboard (landing page)

Pointing your web browser at the root path within your application will open {module-name} on the dashboard.
By default the dashboard has no content other than the top menu.
If you would like a particular controller to open you can set another relative path on the *debugWebModule.dashboard* property.
The path should not contain the root path prefix.

== Securing debug web
By default the {module-name} takes care of securing the debug endpoints if {spring-security-module-url}[SpringSecurityModule] is active.
The username and password can be configured with the `debugWebModule.security.username` and `debugWebModule.security.password` property.
A whiletist of IP addresses can be configured using the `debugWebModule.security.ip-addresses` property.
This is a comma separated list of IP addresses or sub-nets.
These IP addresses will *always* have access to the root path.

Default security can be disabled by setting `debugWebModule.security.enabled` to `false`.
Securing can then easily be done on a web-server level or using custom Spring security configuration.

.Example securing debug web with Spring security
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Configuration
public class DebugWebSecurityConfiguration extends SpringSecurityWebConfigurerAdapter
{
	@Autowired
	private DebugWeb debugWeb;

	@Override
	public void configure( AuthenticationManagerBuilder auth ) throws Exception {
		auth.inMemoryAuthentication()
			.withUser( "debug" )
			.password( "debug" )
			.roles( "DEBUG_USER" );
	}

	@Override
	public void configure( HttpSecurity http ) throws Exception {
		http.antMatcher( debugWeb.path( "/**" ) )
		    .authorizeRequests().anyRequest().hasRole( "DEBUG_USER" )
		    .and()
		    .formLogin().disable()
		    .httpBasic()
		    .and()
		    .sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS )
		    .and()
		    .csrf().disable();
	}
}
----

[[default-debug-controllers]]
== Default debug controllers
Out of the box {module-name} provides some default debug controllers.  These are all available through the top menu.

=== Section: Servlet context
Lists the servlets and filters registered on the servlet context.

=== Section: Across
.Context browser
Allows you to introspect the running `AcrossContext`.
You can navigate the entire `ApplicationContext` hierarchy, see the modules registered in the Across context along with the beans they created (and expose) as well as the configuration properties visible within each module.

As some properties contain sensitive data (for example passwords), it is possible to mask property values based on the property name.
By default all property names containing *password* or *secret* will have their values masked.
Additional rules can be configured with *debugWebModule.properties.masks* or *debugWebModule.properties.masked-properties*.

.AcrossWebModule: Handlers and Interceptors
_Handlers_ lists the different request mapping endoints grouped by their handler mappings.  _Interceptors_ lists the
mapped and unmapped interceptors that apply to a particular handler mapping.

=== Section: DataSources
Lists database drivers and registered datasources with some datasource statistics.

=== Section: Threads and stack
Lists the current threads with their stack trace.

[[creating-your-own]]
== Creating your own debug controller

=== @DebugWebController
Debug web controllers are just like any other controller bean with `RequestMapping` methods, except they are annotated
with `@DebugWebController` instead of the standard `@Controller`.  Any bean annotated with `@DebugWebController`
will be picked up by the {module-name} and will have its mappings prefixed with the debug web root path.

.Simple custom debug web controller mapped on /ROOT_PATH/test
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@DebugWebController
@AcrossDepends(required = "DebugWebModule")
public class DebugEhcacheController
{
	@RequestMapping(value = "/test", method = RequestMethod.GET)
	public String test() {
		return "th/mymodule/debug/test";
	}
}
----

=== Thymeleaf template
Unless a named template is specified, the default Thymeleaf template from debug web will be applied to the output.
The default template will add a top menu for all registered debug web controllers.  Like any Across web Thymeleaf template,
this implementation requires you to put the actual output in a _content_ fragment.

.A Thymeleaf view file for my controller
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
	<title>My test debug controller</title>
</head>
<body th:fragment="content">
	This is a test debug controller.
</body>
</html>
----

If you need additional javascript or custom CSS, you can register it using the `WebResourceRegistry` and it will
automatically be added to the output by the layout template.

.Adding custom CSS with the WebResourceRegistry
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@DebugWebController
@AcrossDepends(required = "DebugWebModule")
public class DebugEhcacheController
{
	@ModelAttribute
	public void registerCss( WebResourceRegistry registry ) {
		registry.addWithKey( WebResource.CSS, "MyModule", "/css/mymodule/debug.css", WebResource.VIEWS );
	}

	@RequestMapping(value = "/test", method = RequestMethod.GET)
	public String test() {
		return "th/mymodule/debug/test";
	}
}
----

=== Customizing the top menu
The default layout template builds and renders a top menu.  This menu is built by publishing a `DebugMenuEvent`. Any
`AcrossEventHandler` - and all controllers are event handlers by default - can listen for this event and modify the menu.
The menu is built using a `PathBasedMenuBuilder`, allowing the entire menu hierarchy to be specified using a path structure.

NOTE: By default the menu item path is also used as the url for the menu endpoint.  All menu item urls will be processed by
the debug web `WebAppPathResolver` and any relative path will be prefixed with the configured root path.

.Example of registering a new top-level menu item pointing to /ROOT_PATH/test
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@DebugWebController
@AcrossDepends(required = "DebugWebModule")
public class DebugEhcacheController
{
	@Event
	public void registerMenuItem( DebugMenuEvent event ) {
		event.builder().item( "/test", "Test controller" );
	}

	@RequestMapping(value = "/test", method = RequestMethod.GET)
	public String test() {
		return "th/mymodule/debug/test";
	}
}
----

=== Linking to debug web controllers
The actual URL endpoint of debug web controllers depends on the application-specific configured root path.  When implementing
 custom debug web controllers you can ensure your relative links point to the correct controller by running them through
 the `PrefixingPathContext`.  {module-name} has registered a prefixer named _debugWeb_, this prefixer can be used to
 correctly point to a debug web controller from any other controller.

.Relative links from Thymeleaf views
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
	<title>My test debug controller</title>
</head>
<body th:fragment="content">
	Relative to debug web root path:
	* <a th:href="@{#webapp.path('/test')}">when rendered from a debug web controller</a>
	* <a th:href="@{#webapp.path('@debugWeb:/test')}">always</a>
</body>
</html>
----

In code the `DebugWeb` bean - implementation of the `PrefixingPathContext` - can be used to generate the correct URL.

.Example of generating a debug controller redirect
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@DebugWebController
@AcrossDepends(required = "DebugWebModule")
public class DebugEhcacheController
{
	@Autowired
	private DebugWeb debugWeb;

	@RequestMapping(value = "/redirect", method = RequestMethod.GET)
	public String test() {
		return debugWeb.redirect( "/test" );
	}
}
----

=== Adding custom interceptors
If you want to add interceptors only to debug web controllers, you can register them using an instance of
  `DebugWebConfigurerAdapter` or any custom `PrefixingHandlerMappingConfigurer` that supports the _{module-name}_ mapper.

== Customizing debug web template
{module-name} uses a default Thymeleaf layout template that builds the top menu and renders HTML for Bootstrap CSS and
JQuery.  If you wish to replace the default layout, you can wire the `debugWebTemplateRegistry`, register
your own `WebTemplateProcessor` and set it as the default template for all debug web controllers.
Alternatively you can specify any registered `WebTemplateProcessor` by name, using the `@Template` annotation on specific debug web controllers.

NOTE: Because {module-name} uses its own `WebTemplateRegistry`, only templates registered explicitly on the `debugWebTemplateRegistry` bean will be available.

For more details, please see the source code of `com.foreach.across.modules.debugweb.config.DebugWebInterceptorsConfiguration`.

