= EhcacheModule
Arne Vandamme
1.0.1-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 1.0.1-SNAPSHOT
:module-name: EhcacheModule
:module-artifact: ehcache-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/EhcacheModule
:debug-web-module-url: https://foreach.atlassian.net/wiki/display/AX/DebugWebModule

--
Copyright (C) 2014-2015 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
{module-name} provides support for Ehcache in other modules.   It creates an Ehcache cache manager and hooks it up to the Spring `CacheManager` infrastructure.
 The module also provides <<debug-controllers,debug web controllers>> for viewing cache statistics and flushing the caches.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

|===
|Module |Type |Description

|{debug-web-module-url}[DebugWebModule]
|optional
|Enables the <<debug-controllers,debug controllers>>.

|===

=== Module settings

|===
|Property |Type |Description |Default

|ehcacheModule.configurationResource
|`Resource.class`
|Ehcache XML resource file.
|_classpath:ehcache.xml_

|ehcacheModule.configurationObject
|`net.sf.ehcache.config.Configuration.class` or `String.class`
|Configuration class instance or class name.
|_null_

|ehcacheModule.cacheManagerName
|`String.class`
|Name of the CacheManager instance.
|_null_

|ehcacheModule.cacheManagerIsShared
|`boolean`
|Should the created CacheManager be shared at the ClassLoader level.
|_true_

|===

== What's new in this version?
:numbered!:
=== 1.0.1-SNAPSHOT

* The properties prefix has been changed from *ehcache.* to *ehcacheModule.*

=== 1.0.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
[[logger-management]]
== Cache manager
{module-name} requires a valid ehcache configuration to be specified, either via an xml resource (*ehcacheModule.configurationResource* property) or
  a `net.sf.ehcache.config.Configuration` instance (*ehcacheModule.configurationObject* property).  Upon bootstrapping the cache manager will be created and available
  as a Spring `CacheManager` implementation.

{module-name} will also activate support for the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html#cache-annotations[cache related annotations]
in every module.  This would be the equivalent of putting `@EnableCaching` in every module.

TIP: Modules should avoid wiring Ehcache beans directly but use the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring cache abstraction layer].

[[debug-controllers]]
== Debug web controllers
NOTE: Only available if {debug-web-module-url}[DebugWebModule] is present.

When active, {module-name} adds a section *Cache overview*  to the debug menu.  The debug web controller
supports multiple Ehcache cache managers and offers the following functions for each cache manager:

 * see cache statistics
 * browse individual cache items
 * flush caches either individually or per cache manager
 * calculate cache heap size
 * view remote RMI peers if RMI-based cache distribution is enabled

.Calculating cache heap size
Apart from the actual heap size the debug controllers attempt to predict the maximum heap size using linear interpolation.
All heap size values should be considered an estimation as they cannot always be calculated correctly.
